In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
!ls -al

total 20
drwxr-xr-x 1 root root 4096 Aug 30 13:20 .
drwxr-xr-x 1 root root 4096 Aug 30 13:14 ..
drwxr-xr-x 4 root root 4096 Aug 25 13:35 .config
drwx------ 5 root root 4096 Aug 30 13:20 drive
drwxr-xr-x 1 root root 4096 Aug 25 13:35 sample_data


In [4]:
%cd /content/drive/MyDrive/cau_temp

/content/drive/MyDrive/cau_temp


In [5]:
!ls -al

total 122940
-rw------- 1 root root 123989053 Aug 25 08:12 data.zip
-rw------- 1 root root    170995 Aug 30 09:16 FIFA_test.csv
-rw------- 1 root root    465646 Aug 30 11:27 FIFA_train1.csv
-rw------- 1 root root    466238 Aug 30 09:16 FIFA_train.csv
-rw------- 1 root root    701268 Aug 27 05:31 laptops_labeled.zip
-rw------- 1 root root     95700 Aug 30 11:45 value.csv


In [6]:
!head FIFA_train.csv

id,age,continent,position,prefer_foot,reputation,3at_overall,3at_potential,3at_skill_moves,value
0,0.31,0.02,0.03,0,0.05,0.94,0.94,0.04,0.1105
3,0.27,0.01,0,0.01,0.04,0.91,0.93,0.01,0.072
7,0.31,0.02,0.03,0.01,0.05,0.91,0.91,0.03,0.08
8,0.32,0.01,0.01,0.01,0.04,0.91,0.91,0.03,0.051
9,0.25,0.01,0,0.01,0.03,0.9,0.93,0.01,0.068
12,0.32,0.02,0.01,0.01,0.03,0.9,0.9,0.02,0.044
13,0.32,0.01,0.02,0,0.04,0.9,0.9,0.04,0.06
14,0.27,0.01,0.02,0.01,0.03,0.89,0.9,0.02,0.063
18,0.26,0.01,0,0.01,0.03,0.89,0.92,0.01,0.058


In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

raw_data = pd.read_csv("FIFA_train.csv")
data = raw_data.to_numpy()
np.random.shuffle(data)

train_x = data[:,1:9]
train_y = data[:,9:]


In [8]:
print(train_x.shape)
print(train_y.shape)
print(train_x[:5,:])
print(train_y[:5,:])

(8932, 8)
(8932, 1)
[[0.31 0.01 0.   0.01 0.01 0.69 0.69 0.01]
 [0.26 0.01 0.03 0.01 0.01 0.65 0.66 0.02]
 [0.29 0.01 0.02 0.   0.01 0.63 0.63 0.02]
 [0.27 0.01 0.03 0.01 0.02 0.74 0.74 0.03]
 [0.22 0.03 0.02 0.01 0.01 0.6  0.64 0.03]]
[[0.00065]
 [0.00065]
 [0.00029]
 [0.006  ]
 [0.00027]]


In [9]:
raw_data_ = pd.read_csv("FIFA_test.csv")
data_=raw_data_.to_numpy()

test_x=data_[:,1:9]

In [10]:
print(test_x.shape)
print(test_x[:5,:])
print(data_[:5,:1])

(3828, 8)
[[0.33 0.01 0.03 0.01 0.05 0.94 0.94 0.05]
 [0.26 0.02 0.03 0.01 0.05 0.92 0.93 0.05]
 [0.27 0.01 0.02 0.01 0.04 0.91 0.92 0.04]
 [0.27 0.01 0.03 0.01 0.04 0.91 0.91 0.04]
 [0.32 0.01 0.02 0.01 0.04 0.91 0.91 0.04]]
[[1.]
 [2.]
 [4.]
 [5.]
 [6.]]


In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import optimizers
from tensorflow.keras.layers import Dense

model = keras.Sequential()
model.add(Dense(10, activation='relu', input_shape=(8,)))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))

model.compile(optimizer="SGD", loss="mse", metrics=["mae"])
model.summary()

history = model.fit(train_x, train_y, epochs=10000, verbose=0, batch_size=128, validation_split=0.1)



y_ = model.predict(test_x)
y1=y_*1000000000
submission = np.concatenate((data_[:,:1],y1), axis=1)
np.savetxt("submission.csv", submission, delimiter=",", fmt="%.6f")

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_27 (Dense)             (None, 10)                90        
_________________________________________________________________
dense_28 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_29 (Dense)             (None, 1)                 11        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [39]:
!ls -al

total 122949
-rw------- 1 root root 123989053 Aug 25 08:12 data.zip
-rw------- 1 root root    170995 Aug 30 09:16 FIFA_test.csv
-rw------- 1 root root    465646 Aug 30 11:27 FIFA_train1.csv
-rw------- 1 root root    466238 Aug 30 09:16 FIFA_train.csv
-rw------- 1 root root    701268 Aug 27 05:31 laptops_labeled.zip
-rw------- 1 root root    104858 Aug 30 15:37 submission.csv


In [40]:
print(submission[:10])

[[       1.    18893504.515]
 [       2.    19424421.713]
 [       4.    18417650.834]
 [       5.    18826348.707]
 [       6.    16982899.979]
 [      10.    17560729.757]
 [      11.    17584869.638]
 [      15.    17477011.308]
 [      17.    16064150.259]
 [      23.    16535090.283]]


In [41]:
!head submission.csv

1.000000,18893504.515290
2.000000,19424421.712756
4.000000,18417650.833726
5.000000,18826348.707080
6.000000,16982899.978757
10.000000,17560729.756951
11.000000,17584869.638085
15.000000,17477011.308074
17.000000,16064150.258899
23.000000,16535090.282559


# 새 섹션