# IRIS 데이터 분류

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import optimizers
from tensorflow.keras.layers import Dense, Input

In [ ]:
!wget https://raw.githubusercontent.com/dhrim/cau_2021/master/material/deep_learning/iris.csv

--2021-09-09 09:00:45--  https://raw.githubusercontent.com/dhrim/cau_2021/master/material/deep_learning/iris.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2720 (2.7K) [text/plain]
Saving to: ‘iris.csv.3’

iris.csv.3          100%[===================>]   2.66K  --.-KB/s    in 0s      

2021-09-09 09:00:45 (65.7 MB/s) - ‘iris.csv.3’ saved [2720/2720]



In [ ]:
!ls -al
!head iris.csv

total 40
drwxr-xr-x 1 root root 4096 Sep  9 09:00 .
drwxr-xr-x 1 root root 4096 Sep  9 08:53 ..
drwxr-xr-x 4 root root 4096 Sep  1 19:26 .config
-rw-r--r-- 1 root root 2720 Sep  9 08:57 iris.csv
-rw-r--r-- 1 root root 2720 Sep  9 08:59 iris.csv.1
-rw-r--r-- 1 root root 2720 Sep  9 09:00 iris.csv.2
-rw-r--r-- 1 root root 2720 Sep  9 09:00 iris.csv.3
-rw-r--r-- 1 root root 2218 Sep  9 08:57 iris_with_category_index.csv
-rw-r--r-- 1 root root 2218 Sep  9 09:00 iris_with_category_index.csv.1
drwxr-xr-x 1 root root 4096 Sep  1 19:26 sample_data
septal_length,septal_width,petal_length,petal_width,setosa,versicolor,virginica
6.4,2.8,5.6,2.2,0,0,1
5.0,2.3,3.3,1.0,0,1,0
4.9,2.5,4.5,1.7,0,0,1
4.9,3.1,1.5,0.1,1,0,0
5.7,3.8,1.7,0.3,1,0,0
4.4,3.2,1.3,0.2,1,0,0
5.4,3.4,1.5,0.4,1,0,0
6.9,3.1,5.1,2.3,0,0,1
6.7,3.1,4.4,1.4,0,1,0


In [ ]:
iris = pd.read_csv("iris.csv")
iris.head()

septal_length  septal_width  petal_length  ...  setosa  versicolor  virginica
0            6.4           2.8           5.6  ...       0           0          1
1            5.0           2.3           3.3  ...       0           1          0
2            4.9           2.5           4.5  ...       0           0          1
3            4.9           3.1           1.5  ...       1           0          0
4            5.7           3.8           1.7  ...       1           0          0

[5 rows x 7 columns]

In [ ]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   septal_length  120 non-null    float64
 1   septal_width   120 non-null    float64
 2   petal_length   120 non-null    float64
 3   petal_width    120 non-null    float64
 4   setosa         120 non-null    int64  
 5   versicolor     120 non-null    int64  
 6   virginica      120 non-null    int64  
dtypes: float64(4), int64(3)
memory usage: 6.7 KB


In [ ]:
data = iris.to_numpy()
print(data.shape)
print(data[:5])

(120, 7)
[[6.4 2.8 5.6 2.2 0.  0.  1. ]
 [5.  2.3 3.3 1.  0.  1.  0. ]
 [4.9 2.5 4.5 1.7 0.  0.  1. ]
 [4.9 3.1 1.5 0.1 1.  0.  0. ]
 [5.7 3.8 1.7 0.3 1.  0.  0. ]]


In [ ]:
x = data[:,:4]
y = data[:,4:]

split_index = 100

train_x, test_x = x[:split_index], x[split_index:]
train_y, test_y = y[:split_index], y[split_index:]

In [ ]:
model = keras.Sequential()
model.add(Input(4))
model.add(Dense(10, activation='tanh'))
model.add(Dense(10, activation='tanh'))
model.add(Dense(3, activation='softmax'))

In [ ]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(train_x, train_y, epochs=200, verbose=0)

In [ ]:
loss, acc = model.evaluate(test_x, test_y)

print("loss :", loss)
print("acc :", acc)


1/1 [==============================] - 0s 100ms/step - loss: 0.0656 - accuracy: 1.0000
loss : 0.0655723512172699
acc : 1.0


In [ ]:
y_ = model.predict(test_x)
print(y_)
print(np.argmax(y_, axis=1))

[[0.96748424 0.03117989 0.00133594]
 [0.02293573 0.94575524 0.03130902]
 [0.9077266  0.09010788 0.00216558]
 [0.01398178 0.9496784  0.03633992]
 [0.9711345  0.02753814 0.00132739]
 [0.9758733  0.02286812 0.00125855]
 [0.9786174  0.02012268 0.00125977]
 [0.9790127  0.01972041 0.0012669 ]
 [0.02888522 0.9498904  0.02122442]
 [0.9665249  0.0321051  0.00136992]
 [0.00428514 0.14600466 0.84971017]
 [0.01630112 0.91485196 0.06884687]
 [0.9597133  0.03886941 0.00141727]
 [0.00132677 0.021859   0.9768142 ]
 [0.9702928  0.02836292 0.00134428]
 [0.01232413 0.69508094 0.2925949 ]
 [0.01996948 0.9426117  0.03741875]
 [0.96785575 0.03076326 0.00138095]
 [0.9698758  0.02881452 0.00130976]
 [0.01362896 0.9422324  0.04413872]]
[0 1 0 1 0 0 0 0 1 0 2 1 0 2 0 1 1 0 0 1]


# loss categorical_crossentropy

2가지 crossentropy 사용 방법
- categorical_crossentropy
- sparse_categorical_crossentropy

## categorical_crossentropy
y의 값이 one hot encoding인 경우
```
1,0,0
0,1,0
0,0,1
```

출력 레이어 설정
```
model.add(Dense(3, activation="softmax")) # 출력 레이어
```

loss 설정
```
model.compile(..., loss='categorical_crossentropy')
```


## sparse_categorical_crossentropy
y의 값이 one hot encoding인 경우
```
0
1
2
```

출력 레이어 설정
```
model.add(Dense(3, activation="softmax")) # 출력 레이어. 1이 아니라 클래스 수 3
```

loss 설정
```
model.compile(..., loss='sparse_categorical_crossentropy')
```


# iris_dnn with category index

아래의 코드는 dnn_iris_and_optimizer.ipynb의 코드를 기반으로 한다.


In [ ]:
!wget https://raw.githubusercontent.com/dhrim/cau_2021/master/material/deep_learning/iris_with_category_index.csv

--2021-09-09 09:00:48--  https://raw.githubusercontent.com/dhrim/cau_2021/master/material/deep_learning/iris_with_category_index.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2218 (2.2K) [text/plain]
Saving to: ‘iris_with_category_index.csv.2’

iris_with_category_ 100%[===================>]   2.17K  --.-KB/s    in 0s      

2021-09-09 09:00:48 (45.2 MB/s) - ‘iris_with_category_index.csv.2’ saved [2218/2218]



In [ ]:
!ls -al
!head iris_with_category_index.csv

total 44
drwxr-xr-x 1 root root 4096 Sep  9 09:00 .
drwxr-xr-x 1 root root 4096 Sep  9 08:53 ..
drwxr-xr-x 4 root root 4096 Sep  1 19:26 .config
-rw-r--r-- 1 root root 2720 Sep  9 08:57 iris.csv
-rw-r--r-- 1 root root 2720 Sep  9 08:59 iris.csv.1
-rw-r--r-- 1 root root 2720 Sep  9 09:00 iris.csv.2
-rw-r--r-- 1 root root 2720 Sep  9 09:00 iris.csv.3
-rw-r--r-- 1 root root 2218 Sep  9 08:57 iris_with_category_index.csv
-rw-r--r-- 1 root root 2218 Sep  9 09:00 iris_with_category_index.csv.1
-rw-r--r-- 1 root root 2218 Sep  9 09:00 iris_with_category_index.csv.2
drwxr-xr-x 1 root root 4096 Sep  1 19:26 sample_data
septal_length,septal_width,petal_length,petal_width,class
6.4,2.8,5.6,2.2,2
5.0,2.3,3.3,1.0,1
4.9,2.5,4.5,1.7,2
4.9,3.1,1.5,0.1,0
5.7,3.8,1.7,0.3,0
4.4,3.2,1.3,0.2,0
5.4,3.4,1.5,0.4,0
6.9,3.1,5.1,2.3,2
6.7,3.1,4.4,1.4,1


In [ ]:
iris = pd.read_csv("iris_with_category_index.csv")
iris.head()

septal_length  septal_width  petal_length  petal_width  class
0            6.4           2.8           5.6          2.2      2
1            5.0           2.3           3.3          1.0      1
2            4.9           2.5           4.5          1.7      2
3            4.9           3.1           1.5          0.1      0
4            5.7           3.8           1.7          0.3      0

In [ ]:
data = iris.to_numpy()
print(data.shape)
print(data[:5])

(120, 5)
[[6.4 2.8 5.6 2.2 2. ]
 [5.  2.3 3.3 1.  1. ]
 [4.9 2.5 4.5 1.7 2. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.7 3.8 1.7 0.3 0. ]]


In [ ]:
x = data[:,:4]
y = data[:,4:]

split_index = 100

train_x, test_x = x[:split_index], x[split_index:]
train_y, test_y = y[:split_index], y[split_index:]

print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(100, 4)
(100, 1)
(20, 4)
(20, 1)


In [ ]:
model = keras.Sequential()
model.add(Input(4))
model.add(Dense(10, activation='tanh'))
model.add(Dense(10, activation='tanh'))
model.add(Dense(3, activation='softmax')) # 1이 아니고 클래스 수 3이다

# model.compile(optimizer="SGD", loss="categorical_crossentropy", metrics=["accuracy"])
model.compile(optimizer="SGD", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
model.summary()

model.fit(train_x, train_y, epochs=1000, verbose=0, batch_size=20)

loss, acc = model.evaluate(test_x, test_y)
print("loss=", loss)
print("acc=", acc)
              


Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_18 (Dense)             (None, 10)                50        
_________________________________________________________________
dense_19 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_20 (Dense)             (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 93ms/step - loss: 0.0311 - accuracy: 1.0000
loss= 0.03113712929189205
acc= 1.0


In [ ]:
y_ = model.predict(test_x)
print(y_)
print(np.argmax(y_, axis=1))

[[9.9334103e-01 6.3550966e-03 3.0381305e-04]
 [9.2408275e-03 9.8865664e-01 2.1025997e-03]
 [9.8414570e-01 1.5356159e-02 4.9819116e-04]
 [4.3511586e-03 9.9381411e-01 1.8347246e-03]
 [9.9340773e-01 6.2909001e-03 3.0132959e-04]
 [9.9464071e-01 5.0886516e-03 2.7059036e-04]
 [9.9490935e-01 4.8286561e-03 2.6201320e-04]
 [9.9497485e-01 4.7637178e-03 2.6144611e-04]
 [1.4877894e-02 9.8303586e-01 2.0861388e-03]
 [9.9252677e-01 7.1533378e-03 3.1989816e-04]
 [7.6917064e-04 2.8348857e-01 7.1574223e-01]
 [5.0608129e-03 9.9008501e-01 4.8542586e-03]
 [9.9165475e-01 8.0060568e-03 3.3911286e-04]
 [2.3343464e-04 7.2743259e-02 9.2702329e-01]
 [9.9326634e-01 6.4252894e-03 3.0834330e-04]
 [3.0556251e-03 9.3160123e-01 6.5343179e-02]
 [6.4292504e-03 9.9027681e-01 3.2939943e-03]
 [9.9297571e-01 6.7101964e-03 3.1416645e-04]
 [9.9365968e-01 6.0456078e-03 2.9466441e-04]
 [4.5873965e-03 9.9363756e-01 1.7750665e-03]]
[0 1 0 1 0 0 0 0 1 0 2 1 0 2 0 1 1 0 0 1]
